export const global = [
  { name: "Argentina", link: "" },
  { name: "Celina Hilbert", link: "" },
  { name: "Australia", link: "" },
  { name: "Alena Smith Interior Design", link: "" },
  { name: "Andrew Sloan", link: "" },
  { name: "Andrew Vaughan", link: "" },
  { name: "Andy Marks", link: "" },
  { name: "Arielle Breit", link: "" },
  { name: "Art Disrupt", link: "" },
  { name: "Austin Smidt", link: "" },
  { name: "AUTHENTIC DESIGN ALLIANCE (ADA)", link: "" },
  { name: "Ben Rennie", link: "" },
  { name: "BETTER FUTURE", link: "" },
  { name: "Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA", link: "" },
  { name: "Brand & Communications at Edge Impact", link: "" },
  { name: "Breathe Architecture", link: "" },
  { name: "BWD Strategic", link: "" },
  { name: "Cameron Tonkinwise", link: "" },
  { name: "Carbon Creative", link: "" },
  { name: "Carolyn King", link: "" },
  { name: "Celine Waters", link: "" },
  { name: "Charlotte Adams", link: "" },
  { name: "Design by Nature", link: "" },
  { name: "Design Consigned", link: "" },
  { name: "Diadem", link: "" },
  { name: "Dr Michelle Douglas FRSA", link: "" },
  { name: "eco creative agency", link: "" },
  { name: "Ethos Digital Agency", link: "" },
  { name: "Finbar", link: "" },
  { name: "Founded by Design Pty Ltd", link: "" },
  { name: "Frost*", link: "" },
  { name: "Gabriella Wilson", link: "" },
  { name: "Genius Agency", link: "" },
  { name: "Geoff Isaac", link: "" },
  { name: "Glen Barry", link: "" },
  { name: "Glen Barry", link: "" },
  { name: "Gloria Quiroga", link: "" },
  { name: "Good 4 Business", link: "" },
  { name: "Good Design Australia", link: "" },
  { name: "Good Design Australia", link: "" },
  { name: "Goodness", link: "" },
  { name: "Goodsports", link: "" },
  { name: "Hammond Studio", link: "" },
  { name: "Harry Steer", link: "" },
  { name: "Heidi Romano", link: "" },
  { name: "Holonic", link: "" },
  { name: "Hortenzia", link: "" },
  { name: "James Hodgson Design", link: "" },
  { name: "Jas Soh", link: "" },
  { name: "Jeremy Yuille", link: "" },
  { name: "Jo Li Tay", link: "" },
  { name: "John Young", link: "" },
  { name: "Josh Riesel", link: "" },
  { name: "Karina Clarke", link: "" },
  { name: "Katapult Design", link: "" },
  { name: "Kirby C", link: "" },
  { name: "Koskela", link: "" },
  { name: "Leigh Phillips-Brown", link: "" },
  { name: "Leigh-Anne Hepburn", link: "" },
  { name: "Leyla Acaroglu", link: "" },
  { name: "Liane Rossler", link: "" },
  { name: "LPB Designs and Interiors", link: "" },
  { name: "Madeline Johnston", link: "" },
  { name: "Make Tomorrow™", link: "" },
  { name: "Marnie Hawson", link: "" },
  { name: "Martin Tomitsch", link: "" },
  { name: "MEK Studio", link: "" },
  { name: "Mirella Arapian", link: "" },
  { name: "Moffitt.Moffitt.", link: "" },
  { name: "Motherbird", link: "" },
  { name: "Nacara Studio", link: "" },
  { name: "Nila Rezaei", link: "" },
  { name: "Particle Design Studio", link: "" },
  { name: "Philip Ely PhD", link: "" },
  { name: "philo & co", link: "" },
  { name: "Planitree", link: "" },
  { name: "Reny Studio", link: "" },
  { name: "Reny®", link: "" },
  { name: "Ricardo Sosa", link: "" },
  { name: "RK Collective", link: "" },
  { name: "RMIT University", link: "" },
  { name: "Samuel Yu", link: "" },
  { name: "Seek & Design", link: "" },
  { name: "Snug House", link: "" },
  { name: "Society for Responsible Design Inc.", link: "" },
  { name: "Sponge", link: "" },
  { name: "Stephanie Mulder", link: "" },
  { name: "Steve Baty", link: "" },
  { name: "STUDIO PERISCOPE", link: "" },
  { name: "Studio Regina", link: "" },
  { name: "studiospillane", link: "" },
  { name: "Tanisha Maria Naik", link: "" },
  { name: "The Design Thinkers", link: "" },
  { name: "UNEND", link: "" },
  { name: "United Studio", link: "" },
  { name: "vert design", link: "" },
  { name: "Wendy Fountain", link: "" },
  { name: "X+O", link: "" },
  { name: "Ys", link: "" },
  { name: "Zero Co pty Ltd", link: "" },
  { name: "Austria", link: "" },
  { name: "Luain", link: "" },
  { name: "Bangladesh", link: "" },
  { name: "Rifat Anik", link: "" },
  { name: "Belgium", link: "" },
  { name: "Air", link: "" },
  { name: "Blue Kameleon SRL", link: "" },
  { name: "Core Branding", link: "" },
  { name: "Futurewave", link: "" },
  { name: "HIER", link: "" },
  { name: "Orb", link: "" },
  { name: "Brazil", link: "" },
  { name: "Adriana Tamashiro", link: "" },
  { name: "Agatha Martins", link: "" },
  { name: "Alexander Ângelo Guazzelli", link: "" },
  { name: "Alexandre de Oliveira Lot", link: "" },
  { name: "Amanda Lima Neves Scorsolini", link: "" },
  { name: "Ana Luísa Canto", link: "" },
  { name: "Ana Paula Batista", link: "" },
  { name: "Audrey Italo Melo", link: "" },
  { name: "BRQ Digital Solutions", link: "" },
  { name: "Bruna Cerasi", link: "" },
  { name: "Bruna Luiza Schwendler", link: "" },
  { name: "Bruna Mattos", link: "" },
  { name: "Brunna Moura", link: "" },
  { name: "BRUNO FREIRE PERRONE", link: "" },
  { name: "Cacto Publicidade", link: "" },
  { name: "Camila Calegari Marques", link: "" },
  { name: "Camila de Almeida Santos", link: "" },
  { name: "Camila Lozeckyi", link: "" },
  { name: "Carlos Filipe Alves Lima", link: "" },
  { name: "Carlos Ignacio Hernández Tellez", link: "" },
  { name: "Carol Hoffmann", link: "" },
  { name: "CECILIA PACHECO", link: "" },
  { name: "Chelles & Hayashi Design", link: "" },
  { name: "christian ullmann", link: "" },
  { name: "Claudia Mardegan", link: "" },
  { name: "Claudio Pelizari", link: "" },
  { name: "Danton Gravina", link: "" },
  { name: "Denilson Silva", link: "" },
  { name: "Denise Oliveira Martins", link: "" },
  { name: "Design Docol at Docol Sanitaryware", link: "" },
  { name: "Design Team at WIS Learn", link: "" },
  { name: "DI", link: "" },
  { name: "Diego Nunes", link: "" },
  { name: "Diogo Lucato", link: "" },
  { name: "DPO Saudável", link: "" },
  { name: "Echos", link: "" },
  { name: "Eduardo Maia", link: "" },
  { name: "Eliane Quadro", link: "" },
  { name: "Empathy Company", link: "" },
  { name: "Estúdio Atômico", link: "" },
  { name: "Estúdio Guto Requena", link: "" },
  { name: "Estudio Marte", link: "" },
  { name: "Fares Saba Jr", link: "" },
  { name: "Fernanda", link: "" },
  { name: "Fernanda Fidelis", link: "" },
  { name: "Fernanda Romera", link: "" },
   { name: "Fluyd", link: "" },
  { name: "Francisco Albuquerque", link: "" },
  { name: "GABRIEL ESTEVES DE OLIVEIRA LEITAO", link: "" },
  { name: "George Rutherford", link: "" },
  { name: "GIOVANA LORENA FAZIONI", link: "" },
  { name: "Green Mandarin", link: "" },
  { name: "Green Mandarin", link: "" },
  { name: "Greg Lopes", link: "" },
  { name: "IMK Arquitetura e Engenharia", link: "" },
  { name: "Jaakko Tammela", link: "" },
  { name: "Jenifer Rodrigues", link: "" },
  { name: "Juan Solís Gundín", link: "" },
  { name: "JULIA RESENDE", link: "" },
  { name: "Júlia Timponi", link: "" },
  { name: "JULIANA SIDSAMER", link: "" },
  { name: "Julianny aidel rafea", link: "" },
  { name: "Junior Magalhães", link: "" },
  { name: "KAREN TIE KAWAKAMI", link: "" },
  { name: "Karla Scherer", link: "" },
  { name: "Larissa Nunes", link: "" },
  { name: "Leo Eyer", link: "" },
  { name: "Leonardo Lins", link: "" },
  { name: "Lincoln Seragini", link: "" },
  { name: "Lincoln Shiguio", link: "" },
  { name: "Lincoln Shiguio", link: "" },
  { name: "Luciana Shirakawa", link: "" },
  { name: "LUIS FERNANDO OSCAR COSTA", link: "" },
  { name: "Maialu Ferlauto", link: "" },
  { name: "Marcelo F. Pereira Junior", link: "" },
  { name: "Marcelo Sales", link: "" },
  { name: "Marcon Zanin", link: "" },
  { name: "Marcos Vinícius Machado de Oliveira", link: "" },
  { name: "Maria de Fátima Gullino", link: "" },
   { name: "Frazão", link: "" },
  { name: "Maria Elisa Zaia", link: "" },
  { name: "Mariana Fonseca de Souza", link: "" },
  { name: "Mariana Pereira Weber", link: "" },
  { name: "Mateus Bull Furlan", link: "" },
  { name: "Mayra Sasso", link: "" },
  { name: "Nathalia Petta", link: "" },
  { name: "paaassos design studio", link: "" },
  { name: "Pamela Basilio", link: "" },
  { name: "Patricia Watson", link: "" },
  { name: "Paula Cristiani Takahashi", link: "" },
  { name: "Paulo Peres", link: "" },
  { name: "Paulo Santos", link: "" },
  { name: "Pedro Gomes", link: "" },
  { name: "Pedro Martins e Souza", link: "" },
  { name: "Pedro Naif", link: "" },
  { name: "Pedro Pazitto", link: "" },
  { name: "PPTzeiros", link: "" },
  { name: "Raissa Esther", link: "" },
  { name: "Raquel Lima", link: "" },
  { name: "RedBandana Branding and Design", link: "" },
  { name: "Rei Campos Inovação em Serviços", link: "" },
  { name: "Renan Benvenuti", link: "" },
  { name: "Renan Migliorini", link: "" },
  { name: "Renata matos", link: "" },
  { name: "Renato Winnig", link: "" },
  { name: "Robson Zumkeller", link: "" },
  { name: "Robson Zumkeller", link: "" },
  { name: "RODRIGO ANTONIO QUEIROZ COSTA", link: "" },
  { name: "Rodrigo Peixoto", link: "" },
  { name: "Sandra Ribeiro Cameira", link: "" },
  { name: "Simbïo Design", link: "" },
  { name: "Studio Allure", link: "" },
  { name: "tellus", link: "" },
  { name: "Thayane", link: "" },
  { name: "Thiago Barreto", link: "" },
  { name: "Thiago Vieira Marques", link: "" },
  { name: "Thoz", link: "" },
  { name: "tiago taveira", link: "" },
  { name: "Tudo é Acessibilidade", link: "" },
  { name: "UERJ", link: "" },
  { name: "Vagner Trevisan", link: "" },
  { name: "Vanessa Silva", link: "" },
  { name: "Victor Maluhy", link: "" },
  { name: "Victor Mascarenhas", link: "" },
    { name: "VIRGINIA CORNELSEN", link: "" },
  { name: "Visorama", link: "" },
  { name: "Wagner Lúcio", link: "" },
  { name: "weme", link: "" },
  { name: "Bulgaria", link: "" },
  { name: "Ivelina Dimitrova", link: "" },
  { name: "Canada", link: "" },
  { name: "Ardeshir Amini", link: "" },
  { name: "Cense Ltd.", link: "" },
  { name: "Eliane Bowden", link: "" },
  { name: "Fletcher Scott Studio Inc.", link: "" },
  { name: "Meghan Hellstern", link: "" },
  { name: "PiTCH PR", link: "" },
  { name: "PiTCH PR", link: "" },
  { name: "Project 42", link: "" },
  { name: "Ryan Mayer", link: "" },
  { name: "SUPERFORT Creative Agency", link: "" },
  { name: "China", link: "" },
  { name: "Campaign Design", link: "" },
  { name: "Orange Creatives", link: "" },
  { name: "Platform88", link: "" },
  { name: "Colombia", link: "" },
  { name: "Coombo", link: "" },
  { name: "Leticia", link: "" },
  { name: "Croatia", link: "" },
  { name: "Creek and Pine", link: "" },
  { name: "Protagonist agencija", link: "" },
  { name: "Czechia", link: "" },
  { name: "Sandra", link: "" },
  { name: "Denmark", link: "" },
  { name: "BineJoMo Studio", link: "" },
  { name: "CurledDesign", link: "" },
  { name: "Louise Ryberg", link: "" },
  { name: "Make Material ApS", link: "" },
  { name: "Sabin Bors", link: "" },
  { name: "TAWS", link: "" },
    { name: "Finland", link: "" },
  { name: "Diseño y diáspora podcast", link: "" },
  { name: "France", link: "" },
  { name: "Archipel Kyosei at Archipel Kyosei", link: "" },
  { name: "Atelier de recherche temporelle at a-r-t", link: "" },
  { name: "Campus des Métiers et des Qualifications Image et Design Hauts de France", link: "" },
  { name: "Christopher Bellamy", link: "" },
  { name: "CY school of design", link: "" },
  { name: "Kristen", link: "" },
  { name: "LAB'S 214", link: "" },
  { name: "madd-bordeaux", link: "" },
  { name: "OUTERCRAFT", link: "" },
  { name: "Valérie Tortolero", link: "" },
  { name: "Germany", link: "" },
  { name: "Amarjith Sreekumar", link: "" },
  { name: "andreas popp", link: "" },
  { name: "Ashley Scarborough", link: "" },
  { name: "Bendcircular", link: "" },
  { name: "Bureau Braun", link: "" },
  { name: "Gloria Ciceri", link: "" },
  { name: "hoch E", link: "" },
  { name: "JDS", link: "" },
  { name: "Jessica Metro", link: "" },
  { name: "Joshua Stehr", link: "" },
  { name: "Katharina Winter", link: "" },
  { name: "Matt Granger", link: "" },
  { name: "NEW STANDARD.STUDIO", link: "" },
  { name: "Paolo de Jesus", link: "" },
  { name: "Philip Hugle", link: "" },
  { name: "Plan C. Studio", link: "" },
  { name: "Schober+Richter", link: "" },
  { name: "STUDIO CDW", link: "" },
  { name: "The Design & Emotion Lab", link: "" },
  { name: "Thorsten Jonas", link: "" },
  { name: "Tillmann Schrempf", link: "" },
  { name: "White Lime", link: "" },
  { name: "Gibraltar", link: "" },
  { name: "Entain", link: "" },
  { name: "Guatemala", link: "" },
  { name: "Fabrizio Constanza", link: "" },
  { name: "India", link: "" },
  { name: "A BLUNT STORY", link: "" },
  { name: "Aboa Hasa Foundation", link: "" },
  { name: "Dinu Prasanna Kennedy", link: "" },
  { name: "DxE Inc.", link: "" },
  { name: "LOCAL", link: "" },
  { name: "Minto Joy", link: "" },
  { name: "Sai Challa", link: "" },
  { name: "Shona Sinha", link: "" },
  { name: "Shreya Salian", link: "" },
  { name: "Indonesia", link: "" },
  { name: "Andini Putri Pramudya Wardani", link: "" },
  { name: "Nice To Meet You Studio", link: "" },
  { name: "Skemasocial", link: "" },
  { name: "Ireland", link: "" },
  { name: "A Worthy Cause", link: "" },
  { name: "Aaron O'Neill", link: "" },
  { name: "Abigail Smith", link: "" },
  { name: "Alanna Campbell", link: "" },
  { name: "Alessandra Ravida", link: "" },
  { name: "Alkamee", link: "" },
  { name: "Alphabet Soup", link: "" },
  { name: "Anastasiia Chorna", link: "" },
  { name: "Andrew Anderson", link: "" },
  { name: "Babelfís", link: "" },
  { name: "BIEN", link: "" },
  { name: "Billion Studio", link: "" },
  { name: "Bradley: The Brand Agency", link: "" },
  { name: "Bren Byrne", link: "" },
  { name: "Brian Morgan", link: "" },
  { name: "Caio", link: "" },
  { name: "Cairenn", link: "" },
  { name: "Capulet and montague", link: "" },
  { name: "Carlos Garcia", link: "" },
  { name: "Chapter", link: "" },
  { name: "Chart Design Studio", link: "" },
  { name: "Ciara Broujos Design", link: "" },
  { name: "Ciara Layden", link: "" },
  { name: "Ciara Wade", link: "" },
  { name: "Circular Design Institute", link: "" },
  { name: "Claire Dillon", link: "" },
  { name: "Claire Dillon", link: "" },
  { name: "Clare Lynch", link: "" },
  { name: "Claudia Fini", link: "" },
  { name: "Claudine Curran", link: "" },
  { name: "Claudine Leonard Design", link: "" },
  { name: "Clever Ghost at Clever", link: "" },
   { name: "Ghost", link: "" },
  { name: "Cliodhna Ryan", link: "" },
  { name: "Conor Flood", link: "" },
  { name: "Conor Nolan", link: "" },
  { name: "consider it design", link: "" },
  { name: "Context Studio", link: "" },
  { name: "CREW", link: "" },
  { name: "Cróna Connolly", link: "" },
  { name: "CUBE Design", link: "" },
  { name: "Damian Sherlock", link: "" },
  { name: "Dan Eames", link: "" },
  { name: "Danielle Deveney", link: "" },
  { name: "Danielle Townsend", link: "" },
  { name: "David Wall", link: "" },
  { name: "Déanta Studio", link: "" },
  { name: "Declan Behan", link: "" },
  { name: "Design for Sustinability & Circular Economies Certificate at Limerick School of Art & Design , TUS", link: "" },
  { name: "Design Notions", link: "" },
  { name: "Design Partners", link: "" },
  { name: "Design Studio at Maverick Communications", link: "" },
  { name: "Detail Design Studio", link: "" },
  { name: "Digital Factory at ESB", link: "" },
  { name: "Disco Milk", link: "" },
  { name: "Duanna Taylor Rooney", link: "" },
  { name: "Each&Other", link: "" },
  { name: "Éilís Murphy", link: "" },
  { name: "Éimear O'Sullivan", link: "" },
  { name: "Emberlight", link: "" },
  { name: "Emi Daly", link: "" },
  { name: "Emma Nolan", link: "" },
  { name: "EPIC Interpretive Design", link: "" },
  { name: "Fly Bird Design", link: "" },
  { name: "FUSE Graphic Design Ltd", link: "" },
  { name: "Global Creative at Johnson Controls", link: "" },
  { name: "Good As Gold", link: "" },
  { name: "Grace", link: "" },
  { name: "Graphic Design [+] at IADT", link: "" },
  { name: "Graphic Design Communication at LSAD at TUS", link: "" },
  { name: "Griffith College Design", link: "" },
  { name: "Image Now", link: "" },
  { name: "Image Now", link: "" },
  { name: "Imagine Lab", link: "" },
  { name: "Iman", link: "" },
  { name: "Ingrid Smyth", link: "" },
  { name: "Institute of Designers Ireland", link: "" },
  { name: "Isabel Staunton", link: "" },
  { name: "Jamie Whelan", link: "" },
  { name: "Jeffers & Sons", link: "" },
  { name: "Joan Ellison", link: "" },
  { name: "Johanna Legnar", link: "" },
  { name: "John Connolly", link: "" },
  { name: "John Connolly", link: "" },
  { name: "John O'Brien", link: "" },
  { name: "Jonny Willis", link: "" },
  { name: "Kacper Jaroszynski", link: "" },
  { name: "Kalil Dunne", link: "" },
  { name: "Kanupriya Jamwal", link: "" },
  { name: "Karl Smyth", link: "" },
  { name: "Karl Toomey", link: "" },
  { name: "Kate Brangan", link: "" },
  { name: "Katy May O’Sullivan", link: "" },
  { name: "Kelly Hood", link: "" },
  { name: "Lands", link: "" },
  { name: "Lara Hanlon", link: "" },
  { name: "Lisa Zimmermann", link: "" },
  { name: "Lucy Bowen", link: "" },
  { name: "Luke McLaughlin", link: "" },
  { name: "M-CO", link: "" },
  { name: "MAKER", link: "" },
  { name: "Mallory Frye", link: "" },
  { name: "Marguerite", link: "" },
  { name: "Marie Gordon", link: "" },
  { name: "Marino Software", link: "" },
  { name: "Meghan Clapham", link: "" },
  { name: "Melvin Jayson C. Ogbalu", link: "" },
  { name: "Michelle Urban", link: "" },
  { name: "Mike Mahon", link: "" },
  { name: "New Graphic", link: "" },
  { name: "Neworld", link: "" },
  { name: "Oisin MacManus", link: "" },
  { name: "Olivia humphreys", link: "" },
  { name: "On The Dot", link: "" },
  { name: "Open Studio", link: "" },
  { name: "Outburst Design", link: "" },
  { name: "Path", link: "" },
  { name: "Patrick Feeney", link: "" },
  { name: "Paula McEntee", link: "" },
  { name: "Penhouse Design", link: "" },
  { name: "Peter Sheehan Studio", link: "" },
  { name: "Piquant", link: "" },
  { name: "Pixelpod", link: "" },
  { name: "POND Studios", link: "" },
  { name: "Portion Collaborative", link: "" },
  { name: "Post Studio", link: "" },
  { name: "Prof Dip and MA Service Design team at National College of Art and Design", link: "" },
  { name: "Public Design Lab at IADT", link: "" },
  { name: "Purple Peach", link: "" },
  { name: "Raluca Turcanasu", link: "" },
  { name: "Rebecca Wright", link: "" },
  { name: "Rebecca Wright", link: "" },
  { name: "Red Dog", link: "" },
  { name: "Richard Whitty", link: "" },
  { name: "RIFORMA collective", link: "" },
  { name: "Róisín Jordan", link: "" },
  { name: "Ross Harrington", link: "" },
  { name: "Ruairí Crawley", link: "" },
  { name: "Sadhbh Murphy", link: "" },
    { name: "Sasha Sykes Studio", link: "" },
  { name: "Self employed - Nichola Wolfe.com", link: "" },
  { name: "Serena Chille", link: "" },
  { name: "Shane Casey", link: "" },
  { name: "Sharon Maxwell", link: "" },
  { name: "Signal Type Founddry", link: "" },
  { name: "SLMD", link: "" },
  { name: "So Studio", link: "" },
  { name: "Sorcha Fitzgerald", link: "" },
  { name: "Stefan Paz", link: "" },
  { name: "Studio Kosmos", link: "" },
  { name: "Studio Saol", link: "" },
  { name: "studiomir", link: "" },
  { name: "Superfolk", link: "" },
  { name: "Susan Carberry", link: "" },
  { name: "Sweet! Graphic Design", link: "" },
  { name: "The Factory", link: "" },
  { name: "The FACTORY", link: "" },
  { name: "The Public House", link: "" },
  { name: "THINKHOUSE", link: "" },
  { name: "Together We Create", link: "" },
  { name: "Treetop Studio", link: "" },
  { name: "University of Limerick", link: "" },
  { name: "Unthink", link: "" },
  { name: "Wes Trumble Design", link: "" },
  { name: "Wilson Creative", link: "" },
  { name: "Wove", link: "" },
  { name: "Isle of Man", link: "" },
  { name: "Studio Cooper", link: "" },
  { name: "Italy", link: "" },
  { name: "acy", link: "" },
  { name: "chiara de angelis", link: "" },
  { name: "Elisabeth Graf", link: "" },
  { name: "Gianluca Menini", link: "" },
  { name: "Kāvya Raman", link: "" },
  { name: "Michael Brenner", link: "" },
  { name: "Ox design studio", link: "" },
  { name: "Simona Audino", link: "" },
  { name: "Japan", link: "" },
  { name: "Asuka Kondo", link: "" },
  { name: "Latvia", link: "" },
  { name: "Drinking Water", link: "" },
  { name: "Ēvija Kraukle", link: "" },
  { name: "Lebanon", link: "" },
  { name: "Designerwork", link: "" },
  { name: "Lithuania", link: "" },
  { name: "Viktorija", link: "" },
  { name: "Luxembourg", link: "" },
  { name: "Art Square Lab SARL-S SIS", link: "" },
  { name: "Malta", link: "" },
  { name: "Abigail Farrugia", link: "" },
  { name: "Mexico", link: "" },
  { name: "Alex Quinto", link: "" },
  { name: "Gustavo González D’Asseo", link: "" },
  { name: "HD*", link: "" },
  { name: "Monserrat Aranzazú Moreno García", link: "" },
  { name: "Narativ Design", link: "" },
  { name: "Morocco", link: "" },
  { name: "evergreen pixel agency", link: "" },
  { name: "Netherlands", link: "" },
  { name: "Archites", link: "" },
  { name: "Circu Leren", link: "" },
  { name: "Creative Mules", link: "" },
  { name: "Danni Swalef", link: "" },
  { name: "Edwin van Maanen", link: "" },
  { name: "Gabriela Bassa", link: "" },
  { name: "Leon van Hoof", link: "" },
  { name: "Nadine", link: "" },
  { name: "Rg/B", link: "" },
  { name: "Rogier Barendregt", link: "" },
  { name: "Rogier Barendregt", link: "" },
  { name: "Sustainable Digital Design", link: "" },
  { name: "Wessel Jansen", link: "" },
  { name: "New Zealand", link: "" },
  { name: "Andrew Roberts", link: "" },
  { name: "Clark Bardsley Design", link: "" },
  { name: "Dani Bond", link: "" },
  { name: "Nicaragua", link: "" },
  { name: "Bernardo van de Schepop", link: "" },
  { name: "Nigeria", link: "" },
  { name: "Nuel Wogundu", link: "" },
  { name: "Ridwan Awujoola", link: "" },
  { name: "Norway", link: "" },
  { name: "Petchy", link: "" },
  { name: "Respira", link: "" },
  { name: "Pakistan", link: "" },
  { name: "Ali Murtaza", link: "" },
  { name: "Syed Faizan Raza", link: "" },
  { name: "Philippines", link: "" },
  { name: "Darwin Antipolo", link: "" },
  { name: "Jesi Sumeg-ang", link: "" },
  { name: "Mathijs Sterrenburg", link: "" },
  { name: "TAYO Change Agency: House of Culture & Creativity", link: "" },
  { name: "Poland", link: "" },
  { name: "Ergodesign", link: "" },
  { name: "Weronika Wojnarowicz", link: "" },
  { name: "Portugal", link: "" },
  { name: "Afonso Miguel Tomaz Assis dos Santos Januário", link: "" },
  { name: "Bernd Herbert", link: "" },
  { name: "Carolina Borges Sacoto", link: "" },
  { name: "Crystal Campbell", link: "" },
  { name: "Daniela Veloso", link: "" },
  { name: "FERNANDO MENDES", link: "" },
  { name: "Graeme McCree", link: "" },
  { name: "Joana Casaca Lemos LDA", link: "" },
  { name: "Pedro Miguel Gago Pereira", link: "" },
  { name: "Rossouw Oosthuizen", link: "" },
  { name: "Tassiane Castro", link: "" },
  { name: "Romania", link: "" },
  { name: "Alex Ardelean", link: "" },
  { name: "Madalina Hamciuc", link: "" },
  { name: "Singapore", link: "" },
  { name: "Audrey Yang", link: "" },
  { name: "Dignité Brands", link: "" },
  { name: "Slovenia", link: "" },
  { name: "Petra Černe Oven", link: "" },
  { name: "Sito", link: "" },
    { name: "South Africa", link: "" },
  { name: "Duncan Stevens", link: "" },
  { name: "the earth is round", link: "" },
  { name: "Spain", link: "" },
  { name: "Alberto Carnero", link: "" },
  { name: "Banda", link: "" },
  { name: "Blackbot", link: "" },
  { name: "Catalina Estrada", link: "" },
  { name: "David O'Mahony", link: "" },
  { name: "Design Thinkers Group Spain", link: "" },
  { name: "Diego González", link: "" },
  { name: "Edu Gonzalez", link: "" },
  { name: "Elena Martinez", link: "" },
  { name: "estudio flúor", link: "" },
  { name: "Estudio República", link: "" },
  { name: "Federico Víllora", link: "" },
  { name: "Folks", link: "" },
  { name: "Folks Brands", link: "" },
  { name: "Gerard", link: "" },
  { name: "Glenn Goodwin", link: "" },
  { name: "holon coop", link: "" },
  { name: "Jesús Gallent", link: "" },
  { name: "Laura Fernández", link: "" },
  { name: "Lucinda Morrissey", link: "" },
  { name: "María Jesús Bonafonte", link: "" },
  { name: "Mean Creative", link: "" },
  { name: "Monnou", link: "" },
  { name: "MOS. More on Simplicity", link: "" },
  { name: "MUAK STUDIO", link: "" },
  { name: "Nixae", link: "" },
  { name: "PATRICIA SALCEDO", link: "" },
  { name: "The Hatch Studio", link: "" },
  { name: "Sweden", link: "" },
  { name: "Antrop", link: "" },
  { name: "Simone De Vivo", link: "" },
  { name: "Switzerland", link: "" },
  { name: "Blitz & Donner", link: "" },
  { name: "Cerca Research & Design Lab", link: "" },
  { name: "Reform GmbH", link: "" },
  { name: "Sarah Santacroce", link: "" },
  { name: "she explores tech", link: "" },
  { name: "Swiss Design Association", link: "" },
  { name: "Valerie Notter de Rabanal", link: "" },
  { name: "Thailand", link: "" },
  { name: "Tipaponr Tharawongthawat", link: "" },
  { name: "Turkey", link: "" },
  { name: "Bilal Akpinar", link: "" },
  { name: "Gaye Poçan", link: "" },
  { name: "United States", link: "" },
  { name: "2911 Creative LLC d/b/a Missionspring Studio", link: "" },
  { name: "76West", link: "" },
  { name: "Amanda Bauer", link: "" },
  { name: "Analogy", link: "" },
  { name: "Angeline Neo", link: "" },
  { name: "Autumn Dahlia Creative Services LLC", link: "" },
  { name: "Box Clever", link: "" },
  { name: "Brayan", link: "" },
  { name: "Business4Today.com", link: "" },
  { name: "Chameleon Studios", link: "" },
  { name: "Colibrily LLC", link: "" },
  { name: "Damn Good Humans", link: "" },
  { name: "Dayani", link: "" },
  { name: "Design Team at Omura", link: "" },
  { name: "Double Loop Marketing", link: "" },
  { name: "LLC", link: "" },
  { name: "Douglas Flandro", link: "" },
  { name: "Elliott Swigert", link: "" },
  { name: "Fabricio Teixeira", link: "" },
  { name: "Gooey.AI", link: "" },
  { name: "GROUP OF HUMANS", link: "" },
  { name: "Indiblu Creative", link: "" },
  { name: "James Junk", link: "" },
  { name: "Kailyn Nelson", link: "" },
  { name: "Kinship Creative", link: "" },
  { name: "Kristin keilt", link: "" },
  { name: "Lucy Crelli", link: "" },
  { name: "Lwindesign", link: "" },
  { name: "M.S.Architecture - Health and Design at NYIT Health and Design", link: "" },
  { name: "Matterall", link: "" },
  { name: "Mayra Cardoso do Nascimento", link: "" },
  { name: "Michael Weschler Productions", link: "" },
  { name: "Mike Simpson Design", link: "" },
  { name: "Mother’s Tongue", link: "" },
  { name: "Re-nourish", link: "" },
  { name: "Rkive Studio", link: "" },
  { name: "Sara Mckee", link: "" },
  { name: "shannon", link: "" },
  { name: "Social Workers Who Design", link: "" },
  { name: "SPACES", link: "" },
  { name: "Stefan Boublil", link: "" },
  { name: "STORM studio", link: "" },
  { name: "Studio SAKA", link: "" },
  { name: "Style & Entertaining", link: "" },
  { name: "Urna Bloom", link: "" },
  { name: "What if Design", link: "" },
  { name: "WHYWHATIF", link: "" },
  { name: "Uruguay", link: "" },
  { name: "Helen Hartley Consulting", link: "" },
  { name: "Lucia Delgado", link: "" },
  { name: "Upgrade", link: "" },
  { name: "Vietnam", link: "" },
  { name: "Dr Britta Boyer", link: "" },
];
