export const links = [
  { name: "21-87", link: "" },
  { name: "216 Signs", link: "" },
  { name: "31% Wool", link: "" },
  { name: "Aalia Ahamed", link: "" },
  { name: "Abbie Williams", link: "" },
  { name: "ACRE -A Creative", link: "" },
  { name: "Endeavour Ltd", link: "" },
  { name: "Active Matter", link: "" },
  { name: "ACX", link: "" },
  { name: "Adele Kelly", link: "" },
  { name: "AdesignStorie", link: "" },
  { name: "Advocate Design Agency", link: "" },
  { name: "Aetha Design", link: "" },
  { name: "Aileron Design Ltd", link: "" },
  { name: "Alan Pitchforth", link: "" },
  { name: "Alex Kimber Design", link: "" },
  { name: "Alexander Miller", link: "" },
  { name: "Alexandra Lunn Studio", link: "" },
  { name: "Alexandra Lunn Studio", link: "" },
  { name: "Alexie Sommer", link: "" },
  { name: "Alexis Bardini", link: "" },
  { name: "Ali Adair", link: "" },
  { name: "Andrew Carr", link: "" },
  { name: "ANdy Parker", link: "" },
  { name: "Andy Thomton", link: "" },
  { name: "Anja Klüver", link: "" },
  { name: "Annabelle Vuille", link: "" },
  { name: "Apfel", link: "" },
  { name: "Applied Works", link: "" },
  { name: "Biomimicry Innovation Lab", link: "" },
  { name: "Bliss", link: "" },
  { name: "Blunt Crayon", link: "" },
  { name: "Bold Studio", link: "" },
  { name: "Boyle & Perks", link: "" },
  { name: "Brand Narrative at", link: "" },
  { name: "Pentagram", link: "" },
  { name: "Bravand", link: "" },
  { name: "Breezign", link: "" },
  { name: "Bright Signals Design at", link: "" },
  { name: "Bright Signals Ltd_", link: "" },
  { name: "Broadley Creative Ltd", link: "" },
  { name: "Bronwen Rees", link: "" },
  { name: "Buff", link: "" },
  { name: "Butterfly", link: "" },
  { name: "BuyDesign", link: "" },
  { name: "Carter Studio", link: "" },
  { name: "Célibataire", link: "" },
  { name: "Charli Blighton", link: "" },
  { name: "Charli Peake", link: "" },
  { name: "Charlotte Eagle", link: "" },
  { name: "Charlotte Evans", link: "" },
  { name: "Cherry Anderson", link: "" },
  { name: "Freelance Design", link: "" },
  { name: "Chloe Poulter", link: "" },
  { name: "Claire ONeiII", link: "" },
  { name: "Claire Potter Design", link: "" },
  { name: "Clara Greo", link: "" },
  { name: "Clare Lewis", link: "" },
  { name: "Claudiu", link: "" },
  { name: "Clever Ghost", link: "" },
  { name: "Climate Labs", link: "" },
  { name: "Design by Mondial", link: "" },
  { name: "Design Council", link: "" },
  { name: "Design For Good Club", link: "" },
  { name: "Design for Joy", link: "" },
  { name: "Design Nature CIC", link: "" },
  { name: "Design Science", link: "" },
  { name: "Design Truth", link: "" },
  { name: "DesignWright", link: "" },
  { name: "DH Design Studios Ltd", link: "" },
  { name: "Dids Macdonald", link: "" },
  { name: "Dionne Griffith", link: "" },
  { name: "Diploma in Professional", link: "" },
  { name: "Studies at London College", link: "" },
  { name: "of Communication", link: "" },
  { name: "DISOMT", link: "" },
  { name: "Dominik Bini", link: "" },
  { name: "Dr Emma Powell", link: "" },
  { name: "Dr Karl Jeffries", link: "" },
  { name: "Drew Kendrick", link: "" },
  { name: "Driftime@ Media", link: "" },
  { name: "Dylan Wiener", link: "" },
  { name: "ecologicstudio", link: "" },
  { name: "Edmuuund", link: "" },
  { name: "Electro Strategy", link: "" },
  { name: "Element Studio", link: "" },
  { name: "Eleven", link: "" },
  { name: "elise", link: "" },
  { name: "Ella Porter", link: "" },
  { name: "Elle Nelson Design", link: "" },
  { name: "Ellie Burroughs", link: "" },
  { name: "Emily Gorham", link: "" },
  { name: "EMMA BRITTAIN", link: "" },
  { name: "Francis Rowland", link: "" },
  { name: "Frankie Thelwell", link: "" },
  { name: "FranklinT111", link: "" },
  { name: "Future Island-Island at", link: "" },
  { name: "Ulster University-led", link: "" },
  { name: "consortium", link: "" },
  { name: "Future Selves", link: "" },
  { name: "Futurice Ltd", link: "" },
  { name: "Fynn", link: "" },
  { name: "G R Moore Limited", link: "" },
  { name: "63 Creative", link: "" },
  { name: "Gareth Neal Ltd", link: "" },
  { name: "Gareth Wild", link: "" },
  { name: "Garlic Agency", link: "" },
  { name: "Genevieve Bennett Ltd", link: "" },
  { name: "Genuinely Conscious", link: "" },
  { name: "George Chamley", link: "" },
  { name: "George Rowland", link: "" },
  { name: "GET LOST", link: "" },
  { name: "Gianfranco Fagotto", link: "" },
  { name: "Gitta Gschwendtner Ltd", link: "" },
  { name: "Giulia Villa", link: "" },
  { name: "Glen Cutwerk", link: "" },
  { name: "Glimpse", link: "" },
  { name: "Good Design Works", link: "" },
  { name: "Good Stuff Creative", link: "" },
  { name: "Good Will Studios", link: "" },
  { name: "Goodtale", link: "" },
  { name: "Goodwin Hartshom", link: "" },
  { name: "Graduate Studies at", link: "" },
  { name: "College for Creative", link: "" },
  { name: "Studies", link: "" },
  { name: "Isabella", link: "" },
  { name: "Jackie Malcolm", link: "" },
  { name: "Jake Owen", link: "" },
  { name: "James Kindred", link: "" },
  { name: "James Tooze", link: "" },
  { name: "Jamie Pinkham", link: "" },
  { name: "jan lewis creative", link: "" },
  { name: "Jane Penty", link: "" },
  { name: "Jason Bruges Studio", link: "" },
  { name: "Jason Mesut", link: "" },
  { name: "Jemima Duncalf", link: "" },
  { name: "Jess Baxter", link: "" },
  { name: "Jess Francis", link: "" },
  { name: "JK Creative Company", link: "" },
  { name: "Jo Mansfield", link: "" },
  { name: "Joanna boehnert", link: "" },
  { name: "John Gilbert", link: "" },
  { name: "Joseph Folkes", link: "" },
  { name: "Josh Elgood", link: "" },
  { name: "Joshua Tunstill", link: "" },
  { name: "Jude Pullen", link: "" },
  { name: "Juice by Design", link: "" },
  { name: "Justine Wyness", link: "" },
  { name: "Kaelum van der Berg", link: "" },
  { name: "Kai Davis", link: "" },
  { name: "Kaleido Grafik", link: "" },
  { name: "Kaleido Grafik", link: "" },
  { name: "Kanika Kalra", link: "" },
  { name: "Karishma Kusurkar", link: "" },
  { name: "Kathryn Summers", link: "" },
  { name: "Kavya Narayanan", link: "" },
  { name: "Kenny Heard", link: "" },
  { name: "Mainlyphotography Studio", link: "" },
  { name: "Mani I", link: "" },
  { name: "Mantra", link: "" },
  { name: "Mar Mar Co- Studio", link: "" },
  { name: "March Studio Ltd", link: "" },
  { name: "Maria Elina", link: "" },
  { name: "Marion Ratie", link: "" },
  { name: "Mark Hicks", link: "" },
  { name: "Marta De Prisco", link: "" },
  { name: "MARTA ROSSATO", link: "" },
  { name: "INTERIORS", link: "" },
  { name: "Martin Hopkins", link: "" },
  { name: "Martin Price", link: "" },
  { name: "Martin Wright", link: "" },
  { name: "Mat Denney", link: "" },
  { name: "Materialise Interiors", link: "" },
  { name: "Materials Council", link: "" },
  { name: "Materialslnformation Ltd", link: "" },
  { name: "Matt Hollands", link: "" },
  { name: "Matteo Menapace", link: "" },
  { name: "Matter + Perspective", link: "" },
  { name: "Matthew Kilcullen", link: "" },
  { name: "Max Fraser", link: "" },
  { name: "Maya Designer", link: "" },
  { name: "Mia Allers", link: "" },
  { name: "Micha Nicheva", link: "" },
  { name: "Michael James", link: "" },
  { name: "Michael Love Design", link: "" },
  { name: "Michael Norrington", link: "" },
  { name: "Michael Rawling", link: "" },
  { name: "Midnight", link: "" },
  { name: "Minna Takala", link: "" },
  { name: "Ohana Studio Ltd", link: "" },
  { name: "0k deploy", link: "" },
  { name: "Ole Makkesen Designlab", link: "" },
  { name: "Olive Kennington", link: "" },
  { name: "Oliver Lloyd", link: "" },
  { name: "Olivia Harris", link: "" },
  { name: "OneKind Creative", link: "" },
  { name: "Optimist Works", link: "" },
  { name: "Oracle Design", link: "" },
  { name: "Orangery", link: "" },
  { name: "ORCA", link: "" },
  { name: "Other Today", link: "" },
  { name: "OURI Labs", link: "" },
  { name: "OXygen", link: "" },
  { name: "Papaya—Studio", link: "" },
  { name: "Papillon Bleu", link: "" },
  { name: "Paul Bailey", link: "" },
  { name: "Paul Gibson Design", link: "" },
  { name: "Pearson Lloyd", link: "" },
  { name: "People Planet Product", link: "" },
  { name: "Phase Two", link: "" },
  { name: "Pixel Fridge LTD", link: "" },
  { name: "Pollenize CIC", link: "" },
  { name: "Polytechnic", link: "" },
  { name: "Poonum Chauhan", link: "" },
  { name: "Pretty Clever", link: "" },
  { name: "Product Design at", link: "" },
  { name: "University of Brighton", link: "" },
  { name: "Product Design at", link: "" },
  { name: "University of Sussex", link: "" },
  { name: "Product for Net Zero", link: "" },
  { name: "Sheffield Hallam University", link: "" },
  { name: "Simone Cucchi", link: "" },
  { name: "Snook", link: "" },
  { name: "Social Change", link: "" },
  { name: "Sophie Mockridge", link: "" },
  { name: "Sophie Reynolds", link: "" },
  { name: "Sophie Thomas", link: "" },
  { name: "spark & Bell", link: "" },
  { name: "Special Projects", link: "" },
  { name: "Spotless", link: "" },
  { name: "Sruti Gidugu", link: "" },
  { name: "Stefan Bassing", link: "" },
  { name: "Still&Nimble", link: "" },
  { name: "Straight Forward Design", link: "" },
  { name: "Stuart Gough", link: "" },
  { name: "Studio Breuil", link: "" },
  { name: "Studio Casey Joy", link: "" },
  { name: "Studio Elk", link: "" },
  { name: "Studio Elma", link: "" },
  { name: "Studio Every", link: "" },
  { name: "Studio Gallant", link: "" },
  { name: "Studio Joana", link: "" },
  { name: "Studio KICO", link: "" },
  { name: "Studio Mothership", link: "" },
  { name: "Studio Olivers", link: "" },
  { name: "Studio Ology", link: "" },
  { name: "Studio Output", link: "" },
  { name: "Studio Overberg", link: "" },
  { name: "Studio Simple", link: "" },
  { name: "Studio Technical Nature", link: "" },
  { name: "The Manufacturing", link: "" },
  { name: "Technology Centre", link: "" },
  { name: "Theo Dormer", link: "" },
  { name: "Think,'Do", link: "" },
  { name: "Thinkpublic", link: "" },
  { name: "Thom Baker Consultancy", link: "" },
  { name: "Thomas Baraldi Cassaro", link: "" },
  { name: "Thomas Wylam", link: "" },
  { name: "thomas_matthews", link: "" },
  { name: "Thoughtcraft", link: "" },
  { name: "Tijana Tasich", link: "" },
  { name: "Tim Frenneaux & Co", link: "" },
  { name: "Tina Bernstein", link: "" },
  { name: "TLC", link: "" },
  { name: "Tokyo Calm", link: "" },
  { name: "Tokyo Calm", link: "" },
  { name: "Tom Greenwood", link: "" },
  { name: "Tomas Gecim", link: "" },
  { name: "Tommy Papaioannou", link: "" },
  { name: "Tria Design", link: "" },
  { name: "Tristan Palmer Studio", link: "" },
  { name: "Two", link: "" },
  { name: "Two Degrees Studio", link: "" },
  { name: "TY Symi", link: "" },
  { name: "Unboxed", link: "" },
  { name: "Unfound Studio", link: "" },
  { name: "United by Design", link: "" },
  { name: "UnlikelyGenius", link: "" },
  { name: "URGE Collective", link: "" },
  { name: "Vashti Waite", link: "" },
  { name: "Vestre Ltd", link: "" },
  { name: "Vicky Lofthouse", link: "" },
  { name: "Applied Works", link: "/applied-works" },
  { name: "Archetype Accessories", link: "/archetype-accessories" },
  { name: "Arif Yusop", link: "/arif-yusop" },
  { name: "Avery & Brown", link: "/avery--brown" },
  { name: "BA (Hons) Design for", link: "/ba-hons-design-for" },
  { name: "Sustainable Futures at", link: "/sustainable-futures-at" },
  { name: "Arts University", link: "/arts-university" },
  { name: "Boumemouth", link: "/boumemouth" },
  { name: "BA Graphic Design at", link: "/ba-graphic-design-at" },
  { name: "Kingston School of Art", link: "/kingston-school-of-art" },
  { name: "Badfish Labs", link: "/badfish-labs" },
  { name: "Baines Design LTD", link: "/baines-design-ltd" },
  { name: "Barbara Chandler", link: "/barbara-chandler" },
  { name: "Barry Bloye", link: "/barry-bloye" },
  { name: "Batch-Works", link: "/batch-works" },
  { name: "Baxter & Bailey", link: "/baxter--bailey" },
  { name: "Be The Future", link: "/be-the-future" },
  { name: "Beehive Green", link: "/beehive-green" },
  { name: "Ben Clarke", link: "/ben-clarke" },
  { name: "Ben Jessop", link: "/ben-jessop" },
  { name: "Bencium Limited", link: "/bencium-limited" },
  { name: "Benedict Povey", link: "/benedict-povey" },
  { name: "Beta Design Office", link: "/beta-design-office" },
  { name: "BIB Design big fish", link: "/bib-design-big-fish" },
  { name: "Big Motive", link: "/big-motive" },
  { name: "Bill Searle", link: "/bill-searle" },
  { name: "Climate Labs", link: "/climate-labs" },
  { name: "Clive Russell", link: "/clive-russell" },
  { name: "COHDA Design", link: "/cohda-design" },
  { name: "Companion Studio", link: "/companion-studio" },
  { name: "Conscious Hospitality Ltd", link: "/conscious-hospitality-ltd" },
  { name: "Conscious Sourcing", link: "/conscious-sourcing" },
  { name: "Contour", link: "/contour" },
  { name: "Creative at Delarki", link: "/creative-at-delarki" },
  { name: "Creative Concem creative conscience", link: "/creative-concem-creative-conscience" },
  { name: "Creative Joy", link: "/creative-joy" },
  { name: "Creative Wildemess LTD", link: "/creative-wildemess-ltd" },
  { name: "Curious Agency", link: "/curious-agency" },
  { name: "Curious Brand", link: "/curious-brand" },
  { name: "CyDen Ltd", link: "/cyden-ltd" },
  { name: "D Squared Product", link: "/d-squared-product" },
  { name: "Development Ltd", link: "/development-ltd" },
  { name: "Daedalus", link: "/daedalus" },
  { name: "Daryl Wilkinson", link: "/daryl-wilkinson" },
  { name: "Dave Cartledge", link: "/dave-cartledge" },
  { name: "Dave Cuvelot", link: "/dave-cuvelot" },
  { name: "David Fairbrother", link: "/david-fairbrother" },
  { name: "David Sudlow Designers", link: "/david-sudlow-designers" },
  { name: "DEFY Brands", link: "/defy-brands" },
  { name: "Design Activists for", link: "/design-activists-for" },
  { name: "Regenerative Futures", link: "/regenerative-futures" },
  { name: "Design Burger", link: "/design-burger" },
  { name: "Design by Country Ltd", link: "/design-by-country-ltd" },
  { name: "EMMA BRITTAIN", link: "/emma-brittain" },
  { name: "Emma Summerscales emmabakerstudio", link: "/emma-summerscales-emmabakerstudio" },
  { name: "Eniola Ogunsola", link: "/eniola-ogunsola" },
  { name: "Ensemble", link: "/ensemble" },
  { name: "Enviral", link: "/enviral" },
  { name: "Etch", link: "/etch" },
  { name: "Ettive Design", link: "/ettive-design" },
  { name: "Europa", link: "/europa" },
  { name: "Eva Koehle", link: "/eva-koehle" },
  { name: "Everything", link: "/everything" },
  { name: "Everywhere Design", link: "/everywhere-design" },
  { name: "Exeter Waste", link: "/exeter-waste" },
  { name: "F VENZANO", link: "/f-venzano" },
  { name: "Fairground Studio", link: "/fairground-studio" },
  { name: "Farrah & Pearce Ltd", link: "/farrah--pearce-ltd" },
  { name: "FearNaught", link: "/fearnaught" },
  { name: "Fernanda Rizzo", link: "/fernanda-rizzo" },
  { name: "Ferrgood Studio", link: "/ferrgood-studio" },
  { name: "Few and Far", link: "/few-and-far" },
  { name: "Fighting Talk", link: "/fighting-talk" },
  { name: "Communications", link: "/communications" },
  { name: "Fiona Watkins Design", link: "/fiona-watkins-design" },
  { name: "Limited", link: "/limited" },
  { name: "Fixperts at Forth", link: "/fixperts-at-forth" },
  { name: "Foundation", link: "/foundation" },
  { name: "Founded Design Ltd", link: "/founded-design-ltd" },
  { name: "Fourfeet Design", link: "/fourfeet-design" },
  { name: "Francesca Cook Design", link: "/francesca-cook-design" },
  { name: "Ltd", link: "/ltd" },
  { name: "Studies", link: "/studies" },
  { name: "Graft Creative", link: "/graft-creative" },
  { name: "Green Mat Workshop", link: "/green-mat-workshop" },
  { name: "Green Orbit Digital", link: "/green-orbit-digital" },
  { name: "Green Rooms landscapes & gardens", link: "/green-rooms-landscapes--gardens" },
  { name: "GreenHeights", link: "/greenheights" },
  { name: "Hamish Duncan", link: "/hamish-duncan" },
  { name: "Hamish Makgill", link: "/hamish-makgill" },
  { name: "Han Li", link: "/han-li" },
  { name: "Hannah Pinnock", link: "/hannah-pinnock" },
  { name: "Harriet Beesley", link: "/harriet-beesley" },
  { name: "Harrison Brands Ltd", link: "/harrison-brands-ltd" },
  { name: "Haughton Design", link: "/haughton-design" },
  { name: "Helen Simmons", link: "/helen-simmons" },
  { name: "Hey Low", link: "/hey-low" },
  { name: "Hippo Digital", link: "/hippo-digital" },
  { name: "Hive IT", link: "/hive-it" },
  { name: "Hiyield", link: "/hiyield" },
  { name: "Holmes Studio honours", link: "/holmes-studio-honours" },
  { name: "HOUSE OF HACKNEY", link: "/house-of-hackney" },
  { name: "Hundred Studio", link: "/hundred-studio" },
  { name: "ICE ilka design limited", link: "/ice-ilka-design-limited" },
  { name: "Imagination Factory", link: "/imagination-factory" },
  { name: "Inspirwood", link: "/inspirwood" },
  { name: "INTRA DRIVE LTD", link: "/intra-drive-ltd" },
  { name: "Irina Teti", link: "/irina-teti" },
  { name: "Kenny Heard", link: "/kenny-heard" },
  { name: "Kenwood Design Office (KDO) at Kenwood Limited", link: "/kenwood-design-office-kdo-at-kenwood-limited" },
  { name: "Kim Trow", link: "/kim-trow" },
  { name: "Kinneir Dufort", link: "/kinneir-dufort" },
  { name: "Kirsten Gord", link: "/kirsten-gord" },
  { name: "KLUVERWORKS", link: "/kluverworks" },
  { name: "Kyle Soo", link: "/kyle-soo" },
  { name: "Kyle Stuart Florent Taylor", link: "/kyle-stuart-florent-taylor" },
  { name: "Laura Santamaria", link: "/laura-santamaria" },
  { name: "Laure Rees-Smith", link: "/laure-rees-smith" },
  { name: "Lawrence Zeegen", link: "/lawrence-zeegen" },
  { name: "Layerd-Studio", link: "/layerd-studio" },
  { name: "Leap Design", link: "/leap-design" },
  { name: "Lewis Plummer", link: "/lewis-plummer" },
  { name: "Liam OBrien", link: "/liam-obrien" },
  { name: "Lil Creative Studio", link: "/lil-creative-studio" },
  { name: "Limber Brands", link: "/limber-brands" },
  { name: "Liquid Studio Ltd", link: "/liquid-studio-ltd" },
  { name: "Lobo Creative", link: "/lobo-creative" },
  { name: "LowCarbon", link: "/lowcarbon" },
  { name: "Lucy Carruthers", link: "/lucy-carruthers" },
  { name: "Lucy Watkins", link: "/lucy-watkins" },
  { name: "Luigi Gisolfi", link: "/luigi-gisolfi" },
  { name: "Lyon & Lyon", link: "/lyon--lyon" },
  { name: "MA Sustainable Design at", link: "/ma-sustainable-design-at" },
  { name: "University of Brighton", link: "/university-of-brighton" },
  { name: "Made for the World madeby-studio", link: "/made-for-the-world-madeby-studio" },
  { name: "Magnus Long Studio", link: "/magnus-long-studio" },
  { name: "Minna Takala", link: "/minna-takala" },
  { name: "Mireia Allende", link: "/mireia-allende" },
  { name: "Mitre and Mondays", link: "/mitre-and-mondays" },
  { name: "Mocean", link: "/mocean" },
  { name: "ModularPlastik", link: "/modularplastik" },
  { name: "Monica Oliveira", link: "/monica-oliveira" },
  { name: "MONOMOTIF", link: "/monomotif" },
  { name: "Morrama", link: "/morrama" },
  { name: "Muddy Machines", link: "/muddy-machines" },
  { name: "Muta Futures Studio", link: "/muta-futures-studio" },
  { name: "Nagonic Design Ltd", link: "/nagonic-design-ltd" },
  { name: "Naked Ideas", link: "/naked-ideas" },
  { name: "Nat Hunter", link: "/nat-hunter" },
  { name: "Natalia Benusiglio Stem", link: "/natalia-benusiglio-stem" },
  { name: "Natalie Perkins", link: "/natalie-perkins" },
  { name: "Nefeli Pavlou Musio", link: "/nefeli-pavlou-musio" },
  { name: "Neol-co", link: "/neol-co" },
  { name: "Never Not Ready", link: "/never-not-ready" },
  { name: "Nicola Holden Designs", link: "/nicola-holden-designs" },
  { name: "Nils Aksnes noel douglas", link: "/nils-aksnes-noel-douglas" },
  { name: "Norah Joshi (Lewis)", link: "/norah-joshi-lewis" },
  { name: "Noughts & Ones", link: "/noughts--ones" },
  { name: "NU Creative Ltd", link: "/nu-creative-ltd" },
  { name: "NU Design Spaces", link: "/nu-design-spaces" },
  { name: "Nurture", link: "/nurture" },
  { name: "Objective Studio observeriy", link: "/objective-studio-observeriy" },
  { name: "Octo Design Ltd", link: "/octo-design-ltd" },
  { name: "OGRE Studio", link: "/ogre-studio" },
  { name: "Product for Net Zero", link: "/product-for-net-zero" },
  { name: "Purple Banana", link: "/purple-banana" },
  { name: "QED web design", link: "/qed-web-design" },
  { name: "Rahul Anand", link: "/rahul-anand" },
  { name: "Realise", link: "/realise" },
  { name: "Rebekah Di Palma", link: "/rebekah-di-palma" },
  { name: "ReShaped Landscape", link: "/reshaped-landscape" },
  { name: "Rhapsody Media", link: "/rhapsody-media" },
  { name: "Rhombus Studio", link: "/rhombus-studio" },
  { name: "Ria Hawthom", link: "/ria-hawthom" },
  { name: "Richa Gandhi", link: "/richa-gandhi" },
  { name: "Robin Wong", link: "/robin-wong" },
  { name: "Roddy Clarke", link: "/roddy-clarke" },
  { name: "Rory Cowan", link: "/rory-cowan" },
  { name: "Roundwave", link: "/roundwave" },
  { name: "Ruddocks", link: "/ruddocks" },
  { name: "Ruth Wassermann Ltd", link: "/ruth-wassermann-ltd" },
  { name: "Sabotage", link: "/sabotage" },
  { name: "Sam Judge", link: "/sam-judge" },
  { name: "Samuel Marchant", link: "/samuel-marchant" },
  { name: "Sandrine Herbert-", link: "/sandrine-herbert-" },
  { name: "Razafinjato", link: "/razafinjato" },
  { name: "School of Good Services", link: "/school-of-good-services" },
  { name: "Selesti", link: "/selesti" },
  { name: "Selina Rose", link: "/selina-rose" },
  { name: "Set Studio", link: "/set-studio" },
  { name: "Seth Campbell", link: "/seth-campbell" },
  { name: "Sheffield Creative", link: "/sheffield-creative" },
  { name: "Industries Institute at", link: "/industries-institute-at" },
  { name: "Studio Technical Nature", link: "/studio-technical-nature" },
  { name: "Studio Tom Metcalfe", link: "/studio-tom-metcalfe" },
  { name: "Studio Wood", link: "/studio-wood" },
  { name: "Submarine", link: "/submarine" },
  { name: "Substance", link: "/substance" },
  { name: "Superfried", link: "/superfried" },
  { name: "Susanna Edwards", link: "/susanna-edwards" },
  { name: "Susannah Kabuiku", link: "/susannah-kabuiku" },
  { name: "Sustainable Ventures", link: "/sustainable-ventures" },
  { name: "Design", link: "/design" },
  { name: "Tacit-Tacit", link: "/tacit-tacit" },
  { name: "Takram", link: "/takram" },
  { name: "TAMART", link: "/tamart" },
  { name: "Tempest", link: "/tempest" },
  { name: "TEN by Anatomy HCD", link: "/ten-by-anatomy-hcd" },
  { name: "Teresa Ferreira Studio", link: "/teresa-ferreira-studio" },
  { name: "Terrarium", link: "/terrarium" },
  { name: "The Art and Design", link: "/the-art-and-design" },
  { name: "Consultancy", link: "/consultancy" },
  { name: "The Blooming Platypus", link: "/the-blooming-platypus" },
  { name: "The Creative Bloc", link: "/the-creative-bloc" },
  { name: "The Digital Creative", link: "/the-digital-creative" },
  { name: "London Ltd-", link: "/london-ltd-" },
  { name: "The Discourse", link: "/the-discourse" },
  { name: "THE FOURTH SOLUTION", link: "/the-fourth-solution" },
  { name: "The Landscape", link: "/the-landscape" },
  { name: "The Looking Glass", link: "/the-looking-glass" },
  { name: "Vicky Lofthouse", link: "/vicky-lofthouse" },
  { name: "Mrgile Janssen", link: "/mrgile-janssen" },
  { name: "Visual Print and Design", link: "/visual-print-and-design" },
  { name: "VIVID NINE", link: "/vivid-nine" },
  { name: "Vox Aeris", link: "/vox-aeris" },
  { name: "Vu Online", link: "/vu-online" },
  { name: "We Are Service Works Ltd", link: "/we-are-service-works-ltd" },
  { name: "We Are Systematic", link: "/we-are-systematic" },
  { name: "We Made This Ltd", link: "/we-made-this-ltd" },
  { name: "We Mean This", link: "/we-mean-this" },
  { name: "WEAMO", link: "/weamo" },
  { name: "West9 Design", link: "/west9-design" },
  { name: "White Weft Limited", link: "/white-weft-limited" },
  { name: "Wholegrain Digital", link: "/wholegrain-digital" },
  { name: "Working with Joe Ltd", link: "/working-with-joe-ltd" },
  { name: "Works in Public Ltd v•mw-archetypeaccessories.com", link: "/works-in-public-ltd-vmw-archetypeaccessoriescom" },
  { name: "XTATX Studio", link: "/xtatx-studio" },
  { name: "Yarn Creative yesim tuzun", link: "/yarn-creative-yesim-tuzun" },
  { name: "Yoke design", link: "/yoke-design" },
  { name: "Zebra Growth Limited", link: "/zebra-growth-limited" },
  { name: "Zoe Bather", link: "/zoe-bather" },
  { name: "ZOOZLY", link: "/zoozly" }
];